# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Keep < Formula
  desc "Policy engine for AI agent tool calls"
  homepage "https://majorcontext.com/keep"
  version "0.4.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/majorcontext/keep/releases/download/v0.4.0/keep_0.4.0_darwin_amd64.tar.gz"
      sha256 "48eb563321f00021ae0252d5ff06842cddeb30fafc70058118a74db7847d3ae6"

      define_method(:install) do
        bin.install "keep"
        bin.install "keep-mcp-relay"
        bin.install "keep-llm-gateway"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/majorcontext/keep/releases/download/v0.4.0/keep_0.4.0_darwin_arm64.tar.gz"
      sha256 "a5865dde86116d9726f8b1a249a88bff7e23d0c73453da13631beb575eb2e1fd"

      define_method(:install) do
        bin.install "keep"
        bin.install "keep-mcp-relay"
        bin.install "keep-llm-gateway"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/majorcontext/keep/releases/download/v0.4.0/keep_0.4.0_linux_amd64.tar.gz"
      sha256 "041d5f0e96135c9018e66dd573344820ee46028b6b50ebdad720aa9200689de8"
      define_method(:install) do
        bin.install "keep"
        bin.install "keep-mcp-relay"
        bin.install "keep-llm-gateway"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/majorcontext/keep/releases/download/v0.4.0/keep_0.4.0_linux_arm64.tar.gz"
      sha256 "5c9de599b7b515388ef3319a735d427882e633725c93d50a53ad1155ab8c5776"
      define_method(:install) do
        bin.install "keep"
        bin.install "keep-mcp-relay"
        bin.install "keep-llm-gateway"
      end
    end
  end

  test do
    system "#{bin}/keep", "version"
  end
end
