# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Keep < Formula
  desc "Policy engine for AI agent tool calls"
  homepage "https://majorcontext.com/keep"
  version "0.2.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/majorcontext/keep/releases/download/v0.2.3/keep_0.2.3_darwin_amd64.tar.gz"
      sha256 "411f75d1aa04d2b7df5ffd501d1b290819cfabc81b3c42b66cd515e37a3c7cbd"

      define_method(:install) do
        bin.install "keep"
        bin.install "keep-mcp-relay"
        bin.install "keep-llm-gateway"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/majorcontext/keep/releases/download/v0.2.3/keep_0.2.3_darwin_arm64.tar.gz"
      sha256 "cf16ebe80aed3eed5e44b1e66e8a2cdc918d5e128599072af7be71a874131164"

      define_method(:install) do
        bin.install "keep"
        bin.install "keep-mcp-relay"
        bin.install "keep-llm-gateway"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/majorcontext/keep/releases/download/v0.2.3/keep_0.2.3_linux_amd64.tar.gz"
      sha256 "0bebd8e6c163ad6686b1e2553cb5d19275bb522372f4522a277d9b31a9b07fc9"
      define_method(:install) do
        bin.install "keep"
        bin.install "keep-mcp-relay"
        bin.install "keep-llm-gateway"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/majorcontext/keep/releases/download/v0.2.3/keep_0.2.3_linux_arm64.tar.gz"
      sha256 "b08dbd37f9ba0db818a0af286e8b87d7835a8a7057c86359ffde163306587331"
      define_method(:install) do
        bin.install "keep"
        bin.install "keep-mcp-relay"
        bin.install "keep-llm-gateway"
      end
    end
  end

  test do
    system "#{bin}/keep", "version"
  end
end
