# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Keep < Formula
  desc "Policy engine for AI agent tool calls"
  homepage "https://majorcontext.com/keep"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/majorcontext/keep/releases/download/v0.1.0/keep_0.1.0_darwin_amd64.tar.gz"
      sha256 "386a4c0ee7225b834b3ecc0eb2d743021561101287dd3ab843030e5a365b6e57"

      define_method(:install) do
        bin.install "keep"
        bin.install "keep-mcp-relay"
        bin.install "keep-llm-gateway"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/majorcontext/keep/releases/download/v0.1.0/keep_0.1.0_darwin_arm64.tar.gz"
      sha256 "4ce6b891acd96a2203d2bf8038161d65cb8cc059b5a9a231711feec8ab1534e8"

      define_method(:install) do
        bin.install "keep"
        bin.install "keep-mcp-relay"
        bin.install "keep-llm-gateway"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/majorcontext/keep/releases/download/v0.1.0/keep_0.1.0_linux_amd64.tar.gz"
      sha256 "370c3c57084df2b771286fb66d4ef483642bd91ca057d3dd94baa80f01edab5e"
      define_method(:install) do
        bin.install "keep"
        bin.install "keep-mcp-relay"
        bin.install "keep-llm-gateway"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/majorcontext/keep/releases/download/v0.1.0/keep_0.1.0_linux_arm64.tar.gz"
      sha256 "a31fbe8f35db285f7bee7fb878b7d0d3b29a4a3b15cc3f1b6280a3c07f4343b7"
      define_method(:install) do
        bin.install "keep"
        bin.install "keep-mcp-relay"
        bin.install "keep-llm-gateway"
      end
    end
  end

  test do
    system "#{bin}/keep", "version"
  end
end
