# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Moat < Formula
  desc "Run AI agents in isolated containers with credential injection and full observability"
  homepage "https://majorcontext.com/moat"
  version "0.5.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/majorcontext/moat/releases/download/v0.5.2/moat_0.5.2_darwin_amd64.tar.gz"
      sha256 "f7d56f0d773b2869381021f28c452d95b6b80b3ef69ff9644845598c84d1814e"

      define_method(:install) do
        bin.install "moat"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/majorcontext/moat/releases/download/v0.5.2/moat_0.5.2_darwin_arm64.tar.gz"
      sha256 "221f2e917ee9e56f12b0e76c869f02e3a7c56430a549cde804d39b5e043e64ef"

      define_method(:install) do
        bin.install "moat"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/majorcontext/moat/releases/download/v0.5.2/moat_0.5.2_linux_amd64.tar.gz"
      sha256 "de8b86a50c4fe5afb65522f0c3d7b28c016bf9c6a1c856844a1f57c6c6803944"
      define_method(:install) do
        bin.install "moat"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/majorcontext/moat/releases/download/v0.5.2/moat_0.5.2_linux_arm64.tar.gz"
      sha256 "0b6874d4da468a6ecbb2ffb071fe2ad798a4659c260cc4ea74e5fbacd3f0809c"
      define_method(:install) do
        bin.install "moat"
      end
    end
  end

  test do
    system "#{bin}/moat", "version"
  end
end
