# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Moat < Formula
  desc "Run AI agents in isolated containers with credential injection and full observability"
  homepage "https://majorcontext.com/moat"
  version "0.5.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/majorcontext/moat/releases/download/v0.5.3/moat_0.5.3_darwin_amd64.tar.gz"
      sha256 "6bc8f4a857857052015890c01c1c1d458ff2f89a0b58727b1449662325023a09"

      define_method(:install) do
        bin.install "moat"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/majorcontext/moat/releases/download/v0.5.3/moat_0.5.3_darwin_arm64.tar.gz"
      sha256 "41c345fc505584fe1e39a71d9aa68a1493d20f6be5fe729aa0fd779ea1ada47b"

      define_method(:install) do
        bin.install "moat"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/majorcontext/moat/releases/download/v0.5.3/moat_0.5.3_linux_amd64.tar.gz"
      sha256 "d2f9e75e4408a52e9c4548d3379f9740b0fc3eb72cdd602fc5103302509563f6"
      define_method(:install) do
        bin.install "moat"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/majorcontext/moat/releases/download/v0.5.3/moat_0.5.3_linux_arm64.tar.gz"
      sha256 "88a7763460dd4349369c0001ad7cb476c191548412ad09f3ad906ceb44b75248"
      define_method(:install) do
        bin.install "moat"
      end
    end
  end

  test do
    system "#{bin}/moat", "version"
  end
end
