# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Moat < Formula
  desc "Run AI agents in isolated containers with credential injection and full observability"
  homepage "https://majorcontext.com/moat"
  version "0.8.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/majorcontext/moat/releases/download/v0.8.2/moat_0.8.2_darwin_amd64.tar.gz"
      sha256 "6753791838035c6b9a47c3580871f6d6a5e0a3fa7b4dbdd626cb681ad5ef8771"

      define_method(:install) do
        bin.install "moat"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/majorcontext/moat/releases/download/v0.8.2/moat_0.8.2_darwin_arm64.tar.gz"
      sha256 "4fe585bfc214c437aa35fd77c95c950f771706fc328877d6ab307f46c5406aa6"

      define_method(:install) do
        bin.install "moat"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/majorcontext/moat/releases/download/v0.8.2/moat_0.8.2_linux_amd64.tar.gz"
      sha256 "3892ae1c5d074d356309fc5144e2cf95e9ad7a0b660f389575a5b45c78f9f934"
      define_method(:install) do
        bin.install "moat"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/majorcontext/moat/releases/download/v0.8.2/moat_0.8.2_linux_arm64.tar.gz"
      sha256 "a7faa142320c8a79b7947ebd585aa706171396774b425289d85f0cbf6b99fbfa"
      define_method(:install) do
        bin.install "moat"
      end
    end
  end

  test do
    system "#{bin}/moat", "version"
  end
end
